name: Validator

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Copy code
        uses: actions/checkout@v4

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install htmlhint
        run: npm install -g htmlhint

      - name: validate files
        run: htmlhint "easyTodo/**/*.html"