name: Validation of html

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@4
        with:
          node-version: '20'

      - name: Install validator
        run: npm install -g html-validator-cli

      - name: Validate certain project
        run: html-validator --format=pretty --file="easyTodo/*.html"
