name: Walidacja Projektu Portfolio

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod z repozytorium
        uses: actions/checkout@v4

      - name: Przygotuj Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Zainstaluj HTMLHint
        run: npm install -g htmlhint

      - name: Sprawdź pliki HTML w folderze easyTodo
        run: htmlhint "easyTodo/**/*.html"